### ISSUE TITLE
Increase db import timeout

### ISSUE THREAD

**Issue by dshumakerUT** [unleashedtech/deployer-recipes#17]
Drupal db imports are failing due to timeout being exceeded (passed 300 seconds).

Sample:

> [afa-drupal-production-web0] run locally zcat < backups/databases/afa--default-2022-01-28--15-38-02.sql.gz | fin db import
> [afa-drupal-production-web0] Truncating afa database...
> [afa-drupal-production-web0] mysql: [Warning] Using a password on the command line interface can be insecure.
> [afa-drupal-production-web0] Importing from stdin...
> [afa-drupal-production-web0] mysql: [Warning] Using a password on the command line interface can be insecure.
> [afa-drupal-production-web0]  Deployer\Exception\TimeoutException  in import.php on line 21:
> [afa-drupal-production-web0]
> [afa-drupal-production-web0]   The command "zcat < backups/databases/afa--default-2022-01-28--15-38-02.sql.gz | fin db import" exceeded the timeout of 300 seconds.
> [afa-drupal-production-web0]
> 

Add [timelimit, -1] to this https://github.com/unleashedtech/deployer-recipes/blob/1ec87dffc598ded75451bd7acc558fafd6f74808/src/VirtualMachine/Docksal/Client.php#L23

**Comment by dshumakerUT** [comment]
Looks like we added the timeout to the update and not the import . https://github.com/unleashedtech/deployer-recipes/commit/7427561f4da9198750cdf89feec882bb670ee7b8#diff-418f8421b82ca877a17c404b81c2bb69d7effef5e7c4c55bc9bac28d9e675520R21

**Comment by danshumaker** [comment]
Fixed here https://github.com/unleashedtech/deployer-recipes/blame/8cfbb0efc8b8542d3ab7e3f0da911cdc6ffd5f37/src/VirtualMachine/Docksal/Client.php   .. Closing.
